# Generated by Django 4.1.2 on 2022-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='other_ingredient',
            field=models.CharField(max_length=60),
        ),
    ]
