# Generated by Django 4.1.4 on 2022-12-21 18:03

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_recipe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prepare',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='salt',
            field=models.CharField(blank=True, choices=[('on taste', 'on taste'), ('on eye', 'on eye')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.CharField(choices=[('pork', 'pork'), ('chicken', 'chicken'), ('beef', 'beef'), ('fish', 'fish'), ('seafood', 'seafood'), ('eggs', 'eggs'), ('vegetarian', 'vegetarian'), ('vegan', 'vegan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_photo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
