# Generated by Django 4.1.2 on 2022-12-15 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_cocktail_cocktail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
