# Generated by Django 4.1.4 on 2022-12-21 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_cocktail_cocktail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='prepare',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
