# Generated by Django 4.1.2 on 2022-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultMainIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_ingredient', models.CharField(blank=True, choices=[('non-alcoholic', 'non-alcoholic'), ('vodka', 'vodka'), ('whiskey', 'whiskey'), ('liquors', 'liquors'), ('rum', 'rum'), ('gin', 'gin'), ('tequila', 'tequila')], max_length=30, null=True)),
            ],
        ),
    ]
