# Generated by Django 4.1.2 on 2022-12-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_searchresultmainingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResultMainIngredient',
        ),
    ]
