# Generated by Django 4.1.4 on 2022-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_cocktailcomment_cocktail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
