"""
Django settings for cooking_co project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# TODO
"""
1. Add dirty word validation in Comments models.
2. Add user email and Cocktail/Recipe name in Comments and Likes models.
3. Create moderators app for editing Cocktail/Recipe, comments and likes for "ModeratorsCC" 
   with permissions of this group. To be reached at ./moderators/.
4. On 10 likes user to become part from "AdminCC" and is_staff=True.
5. Add text field in Cocktail/Recipe "method" to describe how to prepare. 
   To be visible only on Cocktail/Recipe Details page
6. Add fields in Recipe "time_to_cook" and "salt",
7. Add page "About us" where to use text for description of project
"""

from pathlib import Path

from django.urls import reverse_lazy
import psycopg2
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yvw8c(fu&@*&!8r$jjzt7*(v2kmj_z5ydf^h*=%osxc4^l4e5@'

# TODO SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'cloudinary',
    # 'oauthadmin',

    'cooking_co.common',
    'cooking_co.accounts',
    'cooking_co.cocktails',
    'cooking_co.recipes'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'oauthadmin.middleware.OauthAdminSessionMiddleware',
]
# SESSION_SERIALIZER = "django.contrib.sessions.serializers.PickleSerializer"

ROOT_URLCONF = 'cooking_co.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cooking_co.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cooking_co_db',
        'USER': 'postgres',
        'PASSWORD': 'bogo123456',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []

else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = (
    BASE_DIR / 'staticfiles',
)

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'mediafiles'

cloudinary.config(
    cloud_name="ddxz8dlr2",
    api_key="759557234311235",
    api_secret="OGccqGcL4TnfqVtI43XnMyG3_K0",
    secure=True,
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Change user model
AUTH_USER_MODEL = 'accounts.AppUser'

LOGIN_URL = reverse_lazy('sign in')
LOGIN_REDIRECT_URL = reverse_lazy('index')
LOGOUT_REDIRECT_URL = reverse_lazy('index')


EMAIL_HOST = 'in-v3.mailjet.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'cooking.coach10@gmail.com'
EMAIL_HOST_PASSWORD = 'Cooking1234.'

EMAIL_BACKEND = 'django_mailjet.backends.MailjetBackend'
MAILJET_API_KEY = 'b9aac7e19efe27f6c3469a1bfe0377e4'
MAILJET_API_SECRET = '34996fda54f5f7fc3b3fcfeced53cffd'

DEFAULT_FROM_EMAIL = 'cooking.coach10@gmail.com'

'''
---------------------------------------------------------------------------------
---------------------------------------------------------------------------------
---------------------------------------------------------------------------------
'''

# """
# Django settings for cooking_co project.
#
# Generated by 'django-admin startproject' using Django 4.1.3.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.1/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.1/ref/settings/
# """
# from pathlib import Path
#
# import cloudinary as cloudinary
# from django.urls import reverse_lazy
# import psycopg2
# import cloudinary
# import cloudinary.uploader
# import cloudinary.api
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# import cloudinary
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-yvw8c(fu&@*&!8r$jjzt7*(v2kmj_z5ydf^h*=%osxc4^l4e5@'
#
# # TODO SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = False
# DEBUG = True
#
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# # Application definition
#
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#
#     'cloudinary',
#     # 'oauthadmin',
#
#     'cooking_co.common',
#     'cooking_co.accounts',
#     'cooking_co.cocktails',
#     'cooking_co.recipes'
# ]
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#
#     # 'oauthadmin.middleware.OauthAdminSessionMiddleware',
# ]
# # SESSION_SERIALIZER = "django.contrib.sessions.serializers.PickleSerializer"
#
# ROOT_URLCONF = 'cooking_co.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates']
#         ,
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'cooking_co.wsgi.application'
#
# # Database
# # https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'cooking_co_db',
#         'USER': 'postgres',
#         'PASSWORD': 'bogo123456',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }
#
# # Password validation
# # https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
#
# if DEBUG:
#     AUTH_PASSWORD_VALIDATORS = []
#
# else:
#     AUTH_PASSWORD_VALIDATORS = [
#         {
#             'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#         },
#         {
#             'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#         },
#         {
#             'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#         },
#         {
#             'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#         },
#     ]
#
# # Internationalization
# # https://docs.djangoproject.com/en/4.1/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.1/howto/static-files/
#
# STATIC_URL = 'static/'
#
# STATICFILES_DIRS = (
#     BASE_DIR / 'staticfiles',
# )
#
# MEDIA_URL = '/media/'
#
# MEDIA_ROOT = BASE_DIR / 'mediafiles'
#
# cloudinary.config(
#     cloud_name="ddxz8dlr2",
#     api_key="759557234311235",
#     api_secret="OGccqGcL4TnfqVtI43XnMyG3_K0",
#     secure=True,
# )
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# # Change user model
# AUTH_USER_MODEL = 'accounts.AppUser'
#
# LOGIN_URL = reverse_lazy('sign in')
# LOGIN_REDIRECT_URL = reverse_lazy('index')
# # LOGOUT_REDIRECT_URL = reverse_lazy('index')
#
#
# EMAIL_HOST = 'in-v3.mailjet.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'cooking.coach10@gmail.com'
# EMAIL_HOST_PASSWORD = 'Cooking1234.'
#
# EMAIL_BACKEND = 'django_mailjet.backends.MailjetBackend'
# MAILJET_API_KEY = 'b9aac7e19efe27f6c3469a1bfe0377e4'
# MAILJET_API_SECRET = '34996fda54f5f7fc3b3fcfeced53cffd'
#
# DEFAULT_FROM_EMAIL = 'cooking.coach10@gmail.com'
# '''
# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------
# '''