# Generated by Django 4.1.2 on 2022-12-11 16:24

import cooking_co.accounts.validators.validate_age_over_16
import cooking_co.accounts.validators.validate_birthdate_not_in_past
import cooking_co.accounts.validators.validate_only_letters
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(validators=[cooking_co.accounts.validators.validate_birthdate_not_in_past.birthday_not_in_past, cooking_co.accounts.validators.validate_age_over_16.at_least_16]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), cooking_co.accounts.validators.validate_only_letters.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), cooking_co.accounts.validators.validate_only_letters.validate_only_letters]),
        ),
    ]
