# Generated by Django 4.1.2 on 2022-12-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_ready_for_moderator_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='ready_for_moderator_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
