# Generated by Django 4.1.2 on 2022-12-15 14:59

import cloudinary.models
import cooking_co.accounts.validators.validate_image_size
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_ready_for_moderator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, validators=[cooking_co.accounts.validators.validate_image_size.validate_file_less_than_5mb]),
            preserve_default=False,
        ),
    ]
