# Generated by Django 4.1.4 on 2022-12-21 17:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
